version: "3.8"

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: mypwd
      POSTGRES_DB:  calendar
    ports:
      - "5432:5432"
    volumes:
      - ./postgresql/migrations:/docker-entrypoint-initdb.d

  go:
    container_name: go
    build:
      context: .
    ports:
      - "55443:55443"
    depends_on:
      - "postgres"
    networks:
      - default
