swagger: "2.0"
info:
  title: Calendar api
  version: 1.0.0
schemes:
- http
paths:
  /ping:
    get:
      responses:
        200:
          description: Ok

  /users/create:
    post:
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/UserInfo'
      responses:
        200:
          description: Ok
          schema:
            $ref: '#/definitions/UsersCreateResponse'
        500:
          description: Creation failed

  /users/info:
    get:
      parameters:
        - in: query
          type: string
          name: user_id
          required: true
      responses:
        200:
          description: Ok
          schema:
             $ref: '#/definitions/UserInfo'
        404:
          description: Not found
        500:
          description: Fetching info failed

# /users/remove:
# /users/edit:

  /users/free_slot:
    post:
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/UsersFreeSlotRequest'
      responses:
        200:
          description: Ok
          schema:
            $ref: '#/definitions/UsersFreeSlotResponse'
        404:
          description: Not found
        500:
          description: Fail


  /event/create:
    post:
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/EventInfo'
      responses:
        200:
          description: Ok
          schema:
            $ref: '#/definitions/EventCreateResponse'
        500:
          description: Creation failed

  /event/room/create:
    post:
      parameters:
        - in: body
          name: body
          required: true
          schema:
            type: object
            additionalProperties: false
            properties:
              room_id:
                type: string
              name:
                type: string
            required:
              - name
      responses:
        200:
          description: Ok
          schema:
            type: object
            additionalProperties: false
            properties:
              room_id:
                type: string
            required:
              - room_id
        500:
          description: Creation failed

  /event/info:
    get:
      parameters:
        - in: query
          type: string
          name: event_id
          required: true
        - in: query
          type: string
          name: user_id
          required: false
      responses:
        200:
          description: Ok
          schema:
            $ref: '#/definitions/EventInfo'
        500:
          description: Creation failed
        404:
          description: Not found
#  /event/edit:

  /user_events:
    get:
      parameters:
        - in: query
          type: string
          name: user_id
          required: true
        - in: query
          type: string
          format: date-time
          name: time_start
          required: true
        - in: query
          type: string
          format: date-time
          name: time_end
          required: true
      responses:
        200:
          description: Ok
          schema:
            $ref: '#/definitions/UserEventsResponse'
        400:
          description: Bad request
        500:
          description: Internal server error

  /invitation/update:
    post:
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/InvitationUpdateRequest'
      responses:
        200:
          description: Ok
        500:
          description: Update failed

definitions:
  ErrorResponse:
    type: object
    additionalProperties: false
    properties:
      message:
        type: string
    required:
      - message

  UsersCreateResponse:
    type: object
    additionalProperties: false
    properties:
      user_id:
        type: string
    required:
      - user_id

  UserInfo:
    type: object
    additionalProperties: false
    properties:
      user_id:
        type: string
      email:
        type: string
      phone:
        type: string
        pattern: '\+\d{8,20}'
      first_name:
        type: string
      last_name:
        type: string
      workday_start:
        type: string
        example: "10:00"
      workday_end:
        type: string
        example: "20:00"
    required:
      - email
      - phone

  UsersFreeSlotRequest:
    type: object
    additionalProperties: false
    properties:
      user_ids:
        type: array
        minItems: 1
        items:
          type: string
      slot_interval_min:
        type: integer
      from:
        type: string
        format: date-time
    required:
      - user_ids
      - slot_interval_min
      - from

  UsersFreeSlotResponse:
    type: object
    additionalProperties: false
    properties:
      time_start:
        type: string
        format: date-time
      time_end:
        type: string
        format: date-time
    required:
      - time_start
      - time_end

  Accepted:
    type: string
    enum:
      - 'yes'
      - 'no'
      - 'maybe'

  Participant:
    type: object
    additionalProperties: false
    properties:
      user_id:
        type: string
      accepted:
        $ref: '#/definitions/Accepted'
    required:
      - user_id

  EventInfo:
    type: object
    additionalProperties: false
    properties:
      event_id:
        type: string
      name:
        type: string
      description:
        type: string
      creator:
        type: string
      participants:
        type: array
        items:
          $ref: '#/definitions/Participant'
      time_start:
        type: string
        format: date-time
      time_end:
        type: string
        format: date-time
      visibility:
        type: string
        enum:
          - all
          - participants
      repeat:
        type: string
        enum:
          - day
          - workday
          - week
          - month
          - year
      event_room:
        type: string
      notifications:
        type: array
        items:
          $ref: '#/definitions/Notification'
      event_link:
        type: string
    required:
      - name
      - creator
      - time_start
      - time_end
      - visibility

  Notification:
    type: object
    additionalProperties: false
    properties:
      before_start:
        type: integer
        minimum: 1
      step:
        type: string
        enum:
          - m
          - h
          - d
          - w
      method:
        type: string
        enum:
          - email
          - sms
          - telegram
    required:
      - before_start
      - step
      - method

  EventCreateResponse:
    type: object
    additionalProperties: false
    properties:
      event_id:
        type: string
    required:
      - event_id

  InvitationUpdateRequest:
    type: object
    additionalProperties: false
    properties:
      user_id:
        type: string
      event_id:
        type: string
      accepted:
        $ref: '#/definitions/Accepted'
    required:
      - user_id
      - event_id
      - accepted

  UserEventsResponse:
    type: object
    additionalProperties: false
    properties:
      event_ids:
        type: array
        items:
          type: string
    required:
      - event_ids

