// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"calendar/models"
)

// GetUserEventsOKCode is the HTTP code returned for type GetUserEventsOK
const GetUserEventsOKCode int = 200

/*GetUserEventsOK Ok

swagger:response getUserEventsOK
*/
type GetUserEventsOK struct {

	/*
	  In: Body
	*/
	Payload *models.UserEventsResponse `json:"body,omitempty"`
}

// NewGetUserEventsOK creates GetUserEventsOK with default headers values
func NewGetUserEventsOK() *GetUserEventsOK {

	return &GetUserEventsOK{}
}

// WithPayload adds the payload to the get user events o k response
func (o *GetUserEventsOK) WithPayload(payload *models.UserEventsResponse) *GetUserEventsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get user events o k response
func (o *GetUserEventsOK) SetPayload(payload *models.UserEventsResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetUserEventsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetUserEventsBadRequestCode is the HTTP code returned for type GetUserEventsBadRequest
const GetUserEventsBadRequestCode int = 400

/*GetUserEventsBadRequest Bad request

swagger:response getUserEventsBadRequest
*/
type GetUserEventsBadRequest struct {
}

// NewGetUserEventsBadRequest creates GetUserEventsBadRequest with default headers values
func NewGetUserEventsBadRequest() *GetUserEventsBadRequest {

	return &GetUserEventsBadRequest{}
}

// WriteResponse to the client
func (o *GetUserEventsBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// GetUserEventsInternalServerErrorCode is the HTTP code returned for type GetUserEventsInternalServerError
const GetUserEventsInternalServerErrorCode int = 500

/*GetUserEventsInternalServerError Internal server error

swagger:response getUserEventsInternalServerError
*/
type GetUserEventsInternalServerError struct {
}

// NewGetUserEventsInternalServerError creates GetUserEventsInternalServerError with default headers values
func NewGetUserEventsInternalServerError() *GetUserEventsInternalServerError {

	return &GetUserEventsInternalServerError{}
}

// WriteResponse to the client
func (o *GetUserEventsInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
