// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"calendar/models"
)

// GetUsersInfoOKCode is the HTTP code returned for type GetUsersInfoOK
const GetUsersInfoOKCode int = 200

/*GetUsersInfoOK Ok

swagger:response getUsersInfoOK
*/
type GetUsersInfoOK struct {

	/*
	  In: Body
	*/
	Payload *models.UserInfo `json:"body,omitempty"`
}

// NewGetUsersInfoOK creates GetUsersInfoOK with default headers values
func NewGetUsersInfoOK() *GetUsersInfoOK {

	return &GetUsersInfoOK{}
}

// WithPayload adds the payload to the get users info o k response
func (o *GetUsersInfoOK) WithPayload(payload *models.UserInfo) *GetUsersInfoOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get users info o k response
func (o *GetUsersInfoOK) SetPayload(payload *models.UserInfo) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetUsersInfoOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetUsersInfoInternalServerErrorCode is the HTTP code returned for type GetUsersInfoInternalServerError
const GetUsersInfoInternalServerErrorCode int = 500

/*GetUsersInfoInternalServerError Fetching info failed

swagger:response getUsersInfoInternalServerError
*/
type GetUsersInfoInternalServerError struct {
}

// NewGetUsersInfoInternalServerError creates GetUsersInfoInternalServerError with default headers values
func NewGetUsersInfoInternalServerError() *GetUsersInfoInternalServerError {

	return &GetUsersInfoInternalServerError{}
}

// WriteResponse to the client
func (o *GetUsersInfoInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
