// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// NewGetUserEventsParams creates a new GetUserEventsParams object
//
// There are no default values defined in the spec.
func NewGetUserEventsParams() GetUserEventsParams {

	return GetUserEventsParams{}
}

// GetUserEventsParams contains all the bound params for the get user events operation
// typically these are obtained from a http.Request
//
// swagger:parameters GetUserEvents
type GetUserEventsParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  Required: true
	  In: query
	*/
	TimeEnd strfmt.DateTime
	/*
	  Required: true
	  In: query
	*/
	TimeStart strfmt.DateTime
	/*
	  Required: true
	  In: query
	*/
	UserID string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetUserEventsParams() beforehand.
func (o *GetUserEventsParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	qTimeEnd, qhkTimeEnd, _ := qs.GetOK("time_end")
	if err := o.bindTimeEnd(qTimeEnd, qhkTimeEnd, route.Formats); err != nil {
		res = append(res, err)
	}

	qTimeStart, qhkTimeStart, _ := qs.GetOK("time_start")
	if err := o.bindTimeStart(qTimeStart, qhkTimeStart, route.Formats); err != nil {
		res = append(res, err)
	}

	qUserID, qhkUserID, _ := qs.GetOK("user_id")
	if err := o.bindUserID(qUserID, qhkUserID, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindTimeEnd binds and validates parameter TimeEnd from query.
func (o *GetUserEventsParams) bindTimeEnd(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("time_end", "query", rawData)
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// AllowEmptyValue: false

	if err := validate.RequiredString("time_end", "query", raw); err != nil {
		return err
	}

	// Format: date-time
	value, err := formats.Parse("date-time", raw)
	if err != nil {
		return errors.InvalidType("time_end", "query", "strfmt.DateTime", raw)
	}
	o.TimeEnd = *(value.(*strfmt.DateTime))

	if err := o.validateTimeEnd(formats); err != nil {
		return err
	}

	return nil
}

// validateTimeEnd carries on validations for parameter TimeEnd
func (o *GetUserEventsParams) validateTimeEnd(formats strfmt.Registry) error {

	if err := validate.FormatOf("time_end", "query", "date-time", o.TimeEnd.String(), formats); err != nil {
		return err
	}
	return nil
}

// bindTimeStart binds and validates parameter TimeStart from query.
func (o *GetUserEventsParams) bindTimeStart(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("time_start", "query", rawData)
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// AllowEmptyValue: false

	if err := validate.RequiredString("time_start", "query", raw); err != nil {
		return err
	}

	// Format: date-time
	value, err := formats.Parse("date-time", raw)
	if err != nil {
		return errors.InvalidType("time_start", "query", "strfmt.DateTime", raw)
	}
	o.TimeStart = *(value.(*strfmt.DateTime))

	if err := o.validateTimeStart(formats); err != nil {
		return err
	}

	return nil
}

// validateTimeStart carries on validations for parameter TimeStart
func (o *GetUserEventsParams) validateTimeStart(formats strfmt.Registry) error {

	if err := validate.FormatOf("time_start", "query", "date-time", o.TimeStart.String(), formats); err != nil {
		return err
	}
	return nil
}

// bindUserID binds and validates parameter UserID from query.
func (o *GetUserEventsParams) bindUserID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("user_id", "query", rawData)
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// AllowEmptyValue: false

	if err := validate.RequiredString("user_id", "query", raw); err != nil {
		return err
	}
	o.UserID = raw

	return nil
}
