// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"calendar/models"
)

// GetEventInfoOKCode is the HTTP code returned for type GetEventInfoOK
const GetEventInfoOKCode int = 200

/*GetEventInfoOK Ok

swagger:response getEventInfoOK
*/
type GetEventInfoOK struct {

	/*
	  In: Body
	*/
	Payload *models.EventInfo `json:"body,omitempty"`
}

// NewGetEventInfoOK creates GetEventInfoOK with default headers values
func NewGetEventInfoOK() *GetEventInfoOK {

	return &GetEventInfoOK{}
}

// WithPayload adds the payload to the get event info o k response
func (o *GetEventInfoOK) WithPayload(payload *models.EventInfo) *GetEventInfoOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get event info o k response
func (o *GetEventInfoOK) SetPayload(payload *models.EventInfo) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetEventInfoOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetEventInfoNotFoundCode is the HTTP code returned for type GetEventInfoNotFound
const GetEventInfoNotFoundCode int = 404

/*GetEventInfoNotFound Not found

swagger:response getEventInfoNotFound
*/
type GetEventInfoNotFound struct {
}

// NewGetEventInfoNotFound creates GetEventInfoNotFound with default headers values
func NewGetEventInfoNotFound() *GetEventInfoNotFound {

	return &GetEventInfoNotFound{}
}

// WriteResponse to the client
func (o *GetEventInfoNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// GetEventInfoInternalServerErrorCode is the HTTP code returned for type GetEventInfoInternalServerError
const GetEventInfoInternalServerErrorCode int = 500

/*GetEventInfoInternalServerError Creation failed

swagger:response getEventInfoInternalServerError
*/
type GetEventInfoInternalServerError struct {
}

// NewGetEventInfoInternalServerError creates GetEventInfoInternalServerError with default headers values
func NewGetEventInfoInternalServerError() *GetEventInfoInternalServerError {

	return &GetEventInfoInternalServerError{}
}

// WriteResponse to the client
func (o *GetEventInfoInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
