// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// NewGetMeetInfoParams creates a new GetMeetInfoParams object
//
// There are no default values defined in the spec.
func NewGetMeetInfoParams() GetMeetInfoParams {

	return GetMeetInfoParams{}
}

// GetMeetInfoParams contains all the bound params for the get meet info operation
// typically these are obtained from a http.Request
//
// swagger:parameters GetMeetInfo
type GetMeetInfoParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  Required: true
	  In: query
	*/
	MeetingID string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetMeetInfoParams() beforehand.
func (o *GetMeetInfoParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	qMeetingID, qhkMeetingID, _ := qs.GetOK("meeting_id")
	if err := o.bindMeetingID(qMeetingID, qhkMeetingID, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindMeetingID binds and validates parameter MeetingID from query.
func (o *GetMeetInfoParams) bindMeetingID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("meeting_id", "query", rawData)
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// AllowEmptyValue: false

	if err := validate.RequiredString("meeting_id", "query", raw); err != nil {
		return err
	}
	o.MeetingID = raw

	return nil
}
