// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetEventInfoHandlerFunc turns a function with the right signature into a get event info handler
type GetEventInfoHandlerFunc func(GetEventInfoParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetEventInfoHandlerFunc) Handle(params GetEventInfoParams) middleware.Responder {
	return fn(params)
}

// GetEventInfoHandler interface for that can handle valid get event info params
type GetEventInfoHandler interface {
	Handle(GetEventInfoParams) middleware.Responder
}

// NewGetEventInfo creates a new http.Handler for the get event info operation
func NewGetEventInfo(ctx *middleware.Context, handler GetEventInfoHandler) *GetEventInfo {
	return &GetEventInfo{Context: ctx, Handler: handler}
}

/* GetEventInfo swagger:route GET /event/info getEventInfo

GetEventInfo get event info API

*/
type GetEventInfo struct {
	Context *middleware.Context
	Handler GetEventInfoHandler
}

func (o *GetEventInfo) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetEventInfoParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
