// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// NewGetEventInfoParams creates a new GetEventInfoParams object
//
// There are no default values defined in the spec.
func NewGetEventInfoParams() GetEventInfoParams {

	return GetEventInfoParams{}
}

// GetEventInfoParams contains all the bound params for the get event info operation
// typically these are obtained from a http.Request
//
// swagger:parameters GetEventInfo
type GetEventInfoParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  Required: true
	  In: query
	*/
	EventID string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetEventInfoParams() beforehand.
func (o *GetEventInfoParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	qEventID, qhkEventID, _ := qs.GetOK("event_id")
	if err := o.bindEventID(qEventID, qhkEventID, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindEventID binds and validates parameter EventID from query.
func (o *GetEventInfoParams) bindEventID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("event_id", "query", rawData)
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// AllowEmptyValue: false

	if err := validate.RequiredString("event_id", "query", raw); err != nil {
		return err
	}
	o.EventID = raw

	return nil
}
