// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PostEventCreateHandlerFunc turns a function with the right signature into a post event create handler
type PostEventCreateHandlerFunc func(PostEventCreateParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostEventCreateHandlerFunc) Handle(params PostEventCreateParams) middleware.Responder {
	return fn(params)
}

// PostEventCreateHandler interface for that can handle valid post event create params
type PostEventCreateHandler interface {
	Handle(PostEventCreateParams) middleware.Responder
}

// NewPostEventCreate creates a new http.Handler for the post event create operation
func NewPostEventCreate(ctx *middleware.Context, handler PostEventCreateHandler) *PostEventCreate {
	return &PostEventCreate{Context: ctx, Handler: handler}
}

/* PostEventCreate swagger:route POST /event/create postEventCreate

PostEventCreate post event create API

*/
type PostEventCreate struct {
	Context *middleware.Context
	Handler PostEventCreateHandler
}

func (o *PostEventCreate) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPostEventCreateParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
