// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PostMeetCreateHandlerFunc turns a function with the right signature into a post meet create handler
type PostMeetCreateHandlerFunc func(PostMeetCreateParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostMeetCreateHandlerFunc) Handle(params PostMeetCreateParams) middleware.Responder {
	return fn(params)
}

// PostMeetCreateHandler interface for that can handle valid post meet create params
type PostMeetCreateHandler interface {
	Handle(PostMeetCreateParams) middleware.Responder
}

// NewPostMeetCreate creates a new http.Handler for the post meet create operation
func NewPostMeetCreate(ctx *middleware.Context, handler PostMeetCreateHandler) *PostMeetCreate {
	return &PostMeetCreate{Context: ctx, Handler: handler}
}

/* PostMeetCreate swagger:route POST /meet/create postMeetCreate

PostMeetCreate post meet create API

*/
type PostMeetCreate struct {
	Context *middleware.Context
	Handler PostMeetCreateHandler
}

func (o *PostMeetCreate) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPostMeetCreateParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
