// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"calendar/models"
)

// PostUsersCreateOKCode is the HTTP code returned for type PostUsersCreateOK
const PostUsersCreateOKCode int = 200

/*PostUsersCreateOK Ok

swagger:response postUsersCreateOK
*/
type PostUsersCreateOK struct {

	/*
	  In: Body
	*/
	Payload *models.UsersCreateResponse `json:"body,omitempty"`
}

// NewPostUsersCreateOK creates PostUsersCreateOK with default headers values
func NewPostUsersCreateOK() *PostUsersCreateOK {

	return &PostUsersCreateOK{}
}

// WithPayload adds the payload to the post users create o k response
func (o *PostUsersCreateOK) WithPayload(payload *models.UsersCreateResponse) *PostUsersCreateOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post users create o k response
func (o *PostUsersCreateOK) SetPayload(payload *models.UsersCreateResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostUsersCreateOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostUsersCreateInternalServerErrorCode is the HTTP code returned for type PostUsersCreateInternalServerError
const PostUsersCreateInternalServerErrorCode int = 500

/*PostUsersCreateInternalServerError Creation failed

swagger:response postUsersCreateInternalServerError
*/
type PostUsersCreateInternalServerError struct {
}

// NewPostUsersCreateInternalServerError creates PostUsersCreateInternalServerError with default headers values
func NewPostUsersCreateInternalServerError() *PostUsersCreateInternalServerError {

	return &PostUsersCreateInternalServerError{}
}

// WriteResponse to the client
func (o *PostUsersCreateInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
