// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PostUsersFreeSlotHandlerFunc turns a function with the right signature into a post users free slot handler
type PostUsersFreeSlotHandlerFunc func(PostUsersFreeSlotParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostUsersFreeSlotHandlerFunc) Handle(params PostUsersFreeSlotParams) middleware.Responder {
	return fn(params)
}

// PostUsersFreeSlotHandler interface for that can handle valid post users free slot params
type PostUsersFreeSlotHandler interface {
	Handle(PostUsersFreeSlotParams) middleware.Responder
}

// NewPostUsersFreeSlot creates a new http.Handler for the post users free slot operation
func NewPostUsersFreeSlot(ctx *middleware.Context, handler PostUsersFreeSlotHandler) *PostUsersFreeSlot {
	return &PostUsersFreeSlot{Context: ctx, Handler: handler}
}

/* PostUsersFreeSlot swagger:route POST /users/free_slot postUsersFreeSlot

PostUsersFreeSlot post users free slot API

*/
type PostUsersFreeSlot struct {
	Context *middleware.Context
	Handler PostUsersFreeSlotHandler
}

func (o *PostUsersFreeSlot) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPostUsersFreeSlotParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
