// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PostInvitationUpdateHandlerFunc turns a function with the right signature into a post invitation update handler
type PostInvitationUpdateHandlerFunc func(PostInvitationUpdateParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostInvitationUpdateHandlerFunc) Handle(params PostInvitationUpdateParams) middleware.Responder {
	return fn(params)
}

// PostInvitationUpdateHandler interface for that can handle valid post invitation update params
type PostInvitationUpdateHandler interface {
	Handle(PostInvitationUpdateParams) middleware.Responder
}

// NewPostInvitationUpdate creates a new http.Handler for the post invitation update operation
func NewPostInvitationUpdate(ctx *middleware.Context, handler PostInvitationUpdateHandler) *PostInvitationUpdate {
	return &PostInvitationUpdate{Context: ctx, Handler: handler}
}

/* PostInvitationUpdate swagger:route POST /invitation/update postInvitationUpdate

PostInvitationUpdate post invitation update API

*/
type PostInvitationUpdate struct {
	Context *middleware.Context
	Handler PostInvitationUpdateHandler
}

func (o *PostInvitationUpdate) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPostInvitationUpdateParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
