// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"calendar/models"
)

// PostEventCreateOKCode is the HTTP code returned for type PostEventCreateOK
const PostEventCreateOKCode int = 200

/*PostEventCreateOK Ok

swagger:response postEventCreateOK
*/
type PostEventCreateOK struct {

	/*
	  In: Body
	*/
	Payload *models.EventCreateResponse `json:"body,omitempty"`
}

// NewPostEventCreateOK creates PostEventCreateOK with default headers values
func NewPostEventCreateOK() *PostEventCreateOK {

	return &PostEventCreateOK{}
}

// WithPayload adds the payload to the post event create o k response
func (o *PostEventCreateOK) WithPayload(payload *models.EventCreateResponse) *PostEventCreateOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post event create o k response
func (o *PostEventCreateOK) SetPayload(payload *models.EventCreateResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostEventCreateOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostEventCreateInternalServerErrorCode is the HTTP code returned for type PostEventCreateInternalServerError
const PostEventCreateInternalServerErrorCode int = 500

/*PostEventCreateInternalServerError Creation failed

swagger:response postEventCreateInternalServerError
*/
type PostEventCreateInternalServerError struct {
}

// NewPostEventCreateInternalServerError creates PostEventCreateInternalServerError with default headers values
func NewPostEventCreateInternalServerError() *PostEventCreateInternalServerError {

	return &PostEventCreateInternalServerError{}
}

// WriteResponse to the client
func (o *PostEventCreateInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
