// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PostInvitationUpdateOKCode is the HTTP code returned for type PostInvitationUpdateOK
const PostInvitationUpdateOKCode int = 200

/*PostInvitationUpdateOK Ok

swagger:response postInvitationUpdateOK
*/
type PostInvitationUpdateOK struct {
}

// NewPostInvitationUpdateOK creates PostInvitationUpdateOK with default headers values
func NewPostInvitationUpdateOK() *PostInvitationUpdateOK {

	return &PostInvitationUpdateOK{}
}

// WriteResponse to the client
func (o *PostInvitationUpdateOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// PostInvitationUpdateInternalServerErrorCode is the HTTP code returned for type PostInvitationUpdateInternalServerError
const PostInvitationUpdateInternalServerErrorCode int = 500

/*PostInvitationUpdateInternalServerError Update failed

swagger:response postInvitationUpdateInternalServerError
*/
type PostInvitationUpdateInternalServerError struct {
}

// NewPostInvitationUpdateInternalServerError creates PostInvitationUpdateInternalServerError with default headers values
func NewPostInvitationUpdateInternalServerError() *PostInvitationUpdateInternalServerError {

	return &PostInvitationUpdateInternalServerError{}
}

// WriteResponse to the client
func (o *PostInvitationUpdateInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
