// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PostEventRoomCreateOKCode is the HTTP code returned for type PostEventRoomCreateOK
const PostEventRoomCreateOKCode int = 200

/*PostEventRoomCreateOK Ok

swagger:response postEventRoomCreateOK
*/
type PostEventRoomCreateOK struct {

	/*
	  In: Body
	*/
	Payload *PostEventRoomCreateOKBody `json:"body,omitempty"`
}

// NewPostEventRoomCreateOK creates PostEventRoomCreateOK with default headers values
func NewPostEventRoomCreateOK() *PostEventRoomCreateOK {

	return &PostEventRoomCreateOK{}
}

// WithPayload adds the payload to the post event room create o k response
func (o *PostEventRoomCreateOK) WithPayload(payload *PostEventRoomCreateOKBody) *PostEventRoomCreateOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post event room create o k response
func (o *PostEventRoomCreateOK) SetPayload(payload *PostEventRoomCreateOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostEventRoomCreateOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostEventRoomCreateInternalServerErrorCode is the HTTP code returned for type PostEventRoomCreateInternalServerError
const PostEventRoomCreateInternalServerErrorCode int = 500

/*PostEventRoomCreateInternalServerError Creation failed

swagger:response postEventRoomCreateInternalServerError
*/
type PostEventRoomCreateInternalServerError struct {
}

// NewPostEventRoomCreateInternalServerError creates PostEventRoomCreateInternalServerError with default headers values
func NewPostEventRoomCreateInternalServerError() *PostEventRoomCreateInternalServerError {

	return &PostEventRoomCreateInternalServerError{}
}

// WriteResponse to the client
func (o *PostEventRoomCreateInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
