// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// EventInfo event info
//
// swagger:model EventInfo
type EventInfo struct {

	// creator
	// Required: true
	Creator *string `json:"creator"`

	// description
	Description string `json:"description,omitempty"`

	// event id
	EventID string `json:"event_id,omitempty"`

	// event link
	EventLink string `json:"event_link,omitempty"`

	// event room
	EventRoom string `json:"event_room,omitempty"`

	// name
	// Required: true
	Name *string `json:"name"`

	// notifications
	Notifications []*Notification `json:"notifications"`

	// participants
	Participants []*Participant `json:"participants"`

	// repeat
	// Enum: [day workday week month year]
	Repeat string `json:"repeat,omitempty"`

	// time end
	// Required: true
	// Format: date-time
	TimeEnd *strfmt.DateTime `json:"time_end"`

	// time start
	// Required: true
	// Format: date-time
	TimeStart *strfmt.DateTime `json:"time_start"`

	// visibility
	// Required: true
	// Enum: [all participants]
	Visibility *string `json:"visibility"`
}

// Validate validates this event info
func (m *EventInfo) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCreator(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateNotifications(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateParticipants(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRepeat(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTimeEnd(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTimeStart(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateVisibility(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *EventInfo) validateCreator(formats strfmt.Registry) error {

	if err := validate.Required("creator", "body", m.Creator); err != nil {
		return err
	}

	return nil
}

func (m *EventInfo) validateName(formats strfmt.Registry) error {

	if err := validate.Required("name", "body", m.Name); err != nil {
		return err
	}

	return nil
}

func (m *EventInfo) validateNotifications(formats strfmt.Registry) error {
	if swag.IsZero(m.Notifications) { // not required
		return nil
	}

	for i := 0; i < len(m.Notifications); i++ {
		if swag.IsZero(m.Notifications[i]) { // not required
			continue
		}

		if m.Notifications[i] != nil {
			if err := m.Notifications[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("notifications" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("notifications" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *EventInfo) validateParticipants(formats strfmt.Registry) error {
	if swag.IsZero(m.Participants) { // not required
		return nil
	}

	for i := 0; i < len(m.Participants); i++ {
		if swag.IsZero(m.Participants[i]) { // not required
			continue
		}

		if m.Participants[i] != nil {
			if err := m.Participants[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("participants" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("participants" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

var eventInfoTypeRepeatPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["day","workday","week","month","year"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		eventInfoTypeRepeatPropEnum = append(eventInfoTypeRepeatPropEnum, v)
	}
}

const (

	// EventInfoRepeatDay captures enum value "day"
	EventInfoRepeatDay string = "day"

	// EventInfoRepeatWorkday captures enum value "workday"
	EventInfoRepeatWorkday string = "workday"

	// EventInfoRepeatWeek captures enum value "week"
	EventInfoRepeatWeek string = "week"

	// EventInfoRepeatMonth captures enum value "month"
	EventInfoRepeatMonth string = "month"

	// EventInfoRepeatYear captures enum value "year"
	EventInfoRepeatYear string = "year"
)

// prop value enum
func (m *EventInfo) validateRepeatEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, eventInfoTypeRepeatPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *EventInfo) validateRepeat(formats strfmt.Registry) error {
	if swag.IsZero(m.Repeat) { // not required
		return nil
	}

	// value enum
	if err := m.validateRepeatEnum("repeat", "body", m.Repeat); err != nil {
		return err
	}

	return nil
}

func (m *EventInfo) validateTimeEnd(formats strfmt.Registry) error {

	if err := validate.Required("time_end", "body", m.TimeEnd); err != nil {
		return err
	}

	if err := validate.FormatOf("time_end", "body", "date-time", m.TimeEnd.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *EventInfo) validateTimeStart(formats strfmt.Registry) error {

	if err := validate.Required("time_start", "body", m.TimeStart); err != nil {
		return err
	}

	if err := validate.FormatOf("time_start", "body", "date-time", m.TimeStart.String(), formats); err != nil {
		return err
	}

	return nil
}

var eventInfoTypeVisibilityPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["all","participants"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		eventInfoTypeVisibilityPropEnum = append(eventInfoTypeVisibilityPropEnum, v)
	}
}

const (

	// EventInfoVisibilityAll captures enum value "all"
	EventInfoVisibilityAll string = "all"

	// EventInfoVisibilityParticipants captures enum value "participants"
	EventInfoVisibilityParticipants string = "participants"
)

// prop value enum
func (m *EventInfo) validateVisibilityEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, eventInfoTypeVisibilityPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *EventInfo) validateVisibility(formats strfmt.Registry) error {

	if err := validate.Required("visibility", "body", m.Visibility); err != nil {
		return err
	}

	// value enum
	if err := m.validateVisibilityEnum("visibility", "body", *m.Visibility); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this event info based on the context it is used
func (m *EventInfo) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateNotifications(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateParticipants(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *EventInfo) contextValidateNotifications(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Notifications); i++ {

		if m.Notifications[i] != nil {
			if err := m.Notifications[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("notifications" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("notifications" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *EventInfo) contextValidateParticipants(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Participants); i++ {

		if m.Participants[i] != nil {
			if err := m.Participants[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("participants" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("participants" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *EventInfo) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *EventInfo) UnmarshalBinary(b []byte) error {
	var res EventInfo
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
