// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// InvitationUpdateRequest invitation update request
//
// swagger:model InvitationUpdateRequest
type InvitationUpdateRequest struct {

	// accepted
	// Required: true
	Accepted *Accepted `json:"accepted"`

	// event id
	// Required: true
	EventID *string `json:"event_id"`

	// user id
	// Required: true
	UserID *string `json:"user_id"`
}

// Validate validates this invitation update request
func (m *InvitationUpdateRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAccepted(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateEventID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUserID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *InvitationUpdateRequest) validateAccepted(formats strfmt.Registry) error {

	if err := validate.Required("accepted", "body", m.Accepted); err != nil {
		return err
	}

	if err := validate.Required("accepted", "body", m.Accepted); err != nil {
		return err
	}

	if m.Accepted != nil {
		if err := m.Accepted.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("accepted")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("accepted")
			}
			return err
		}
	}

	return nil
}

func (m *InvitationUpdateRequest) validateEventID(formats strfmt.Registry) error {

	if err := validate.Required("event_id", "body", m.EventID); err != nil {
		return err
	}

	return nil
}

func (m *InvitationUpdateRequest) validateUserID(formats strfmt.Registry) error {

	if err := validate.Required("user_id", "body", m.UserID); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this invitation update request based on the context it is used
func (m *InvitationUpdateRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateAccepted(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *InvitationUpdateRequest) contextValidateAccepted(ctx context.Context, formats strfmt.Registry) error {

	if m.Accepted != nil {
		if err := m.Accepted.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("accepted")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("accepted")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *InvitationUpdateRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *InvitationUpdateRequest) UnmarshalBinary(b []byte) error {
	var res InvitationUpdateRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
