// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// UserEventsResponse user events response
//
// swagger:model UserEventsResponse
type UserEventsResponse struct {

	// event ids
	// Required: true
	EventIds []string `json:"event_ids"`
}

// Validate validates this user events response
func (m *UserEventsResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateEventIds(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *UserEventsResponse) validateEventIds(formats strfmt.Registry) error {

	if err := validate.Required("event_ids", "body", m.EventIds); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this user events response based on context it is used
func (m *UserEventsResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *UserEventsResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UserEventsResponse) UnmarshalBinary(b []byte) error {
	var res UserEventsResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
